### ISSUE TITLE
Something you might be interested in...

### ISSUE THREAD

**Issue by canselcik** [neg4n/trickster#3]
Hey,

Saw your post on UC and wanted to share you my Rust port of vmread.

https://github.com/canselcik/libvirtdma

Sounds like we have been looking into similar things lately.

Going to fully port the kernel module as well to Rust once that proposal reaches a certain point. Take a look at the cli utility I have with it that functions as a demo. It also has some RustClient data structures, patterns and offsets.

**Comment by neg4n** [comment]
Hey @canselcik 

I have not posted trickster on UC yet.
Anyways, thanks for letting me know about existence of your project.
I'll check it out :sunglasses:

**Comment by canselcik** [comment]
I was so sure I saw it on UC. How did I arrive here then. :)
Maybe searching some keywords and constants along the way brought me here. :)
